import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  'https://bmehxrasbjwnqotxjroc.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtZWh4cmFzYmp3bnFvdHhqcm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMDE2OTgsImV4cCI6MjA4NjU3NzY5OH0.tUK14D8GdVSVSbWaOq8Lz9i0Y0D08IZLfEr9ES28Ukc'
);

const races = [
  // ===================== IRONMAN (Full Distance) =====================
  {
    slug: 'ironman-france-nice',
    name: 'Ironman France Nice',
    date: '2026-06-28',
    location: 'Nice, Alpes-Maritimes',
    city: 'Nice',
    department: 'Alpes-Maritimes',
    region: 'Provence-Alpes-Côte d\'Azur',
    country: 'France',
    latitude: 43.7102,
    longitude: 7.2620,
    discipline: 'triathlon',
    category: 'Ironman',
    swim_distance: 3800,
    bike_distance: 180000,
    run_distance: 42195,
    total_distance: 226000,
    bike_elevation: 2400,
    run_elevation: 50,
    total_elevation: 2450,
    price_euros: 655,
    max_participants: 2500,
    time_limit_hours: 16,
    description: 'L\'un des parcours les plus mythiques au monde. Nage dans la Baie des Anges au départ de la Plage des Ponchettes. Vélo très exigeant dans l\'arrière-pays niçois avec 2400m de dénivelé à travers le Parc Naturel des PréAlpes d\'Azur. Marathon plat mais chaud sur la Promenade des Anglais (4 boucles).',
    tagline: 'L\'aigle des Ironman',
    image_gradient: 'bg-gradient-to-br from-blue-600 to-cyan-500',
    avg_temp_celsius: 28,
    avg_water_temp_celsius: 23,
    avg_wind_kmh: 15,
    record_men: '8:08:59 — Frederik Van Lierde',
    record_women: '9:11:39 — Corinne Abraham',
    tags: ['Mythique', 'Montagne', 'Bord de mer', 'Technique'],
    website_url: 'https://www.ironman.com/im-france',
    finishers_url: 'https://www.finishers.com/course/ironman-france-nice',
  },
  {
    slug: 'ironman-cascais',
    name: 'Ironman Cascais Portugal',
    date: '2026-10-18',
    location: 'Cascais, Lisbonne',
    city: 'Cascais',
    department: null,
    region: 'Lisbonne',
    country: 'Portugal',
    latitude: 38.6968,
    longitude: -9.4207,
    discipline: 'triathlon',
    category: 'Ironman',
    swim_distance: 3800,
    bike_distance: 180000,
    run_distance: 42195,
    total_distance: 226000,
    bike_elevation: 1200,
    run_elevation: 150,
    total_elevation: 1350,
    price_euros: 640,
    max_participants: 2000,
    time_limit_hours: 17,
    description: 'Ironman sur la côte atlantique portugaise. Nage en mer le long de la plage de Cascais. Parcours vélo roulant le long de la côte avec des montées modérées dans la Serra de Sintra. Marathon le long de la promenade maritime avec vue sur l\'océan.',
    tagline: 'Le charme de l\'Atlantique',
    image_gradient: 'bg-gradient-to-br from-orange-500 to-amber-600',
    avg_temp_celsius: 22,
    avg_water_temp_celsius: 18,
    avg_wind_kmh: 18,
    record_men: null,
    record_women: null,
    tags: ['Bord de mer', 'International', 'Automne', 'Roulant'],
    website_url: 'https://www.ironman.com/im-cascais',
    finishers_url: null,
  },

  // ===================== XL =====================
  {
    slug: 'embrunman',
    name: 'Embrunman',
    date: '2026-08-15',
    location: 'Embrun, Hautes-Alpes',
    city: 'Embrun',
    department: 'Hautes-Alpes',
    region: 'Provence-Alpes-Côte d\'Azur',
    country: 'France',
    latitude: 44.5640,
    longitude: 6.4959,
    discipline: 'triathlon',
    category: 'XL',
    swim_distance: 3800,
    bike_distance: 188000,
    run_distance: 42195,
    total_distance: 234000,
    bike_elevation: 5000,
    run_elevation: 400,
    total_elevation: 5400,
    price_euros: 350,
    max_participants: 800,
    time_limit_hours: 16,
    description: 'Le triathlon le plus dur au monde. Nage dans le lac de Serre-Ponçon. Vélo mythique avec 5000m de D+ incluant le Col d\'Izoard. Course à pied sur 3 boucles vallonnées autour d\'Embrun. Seuls les athlètes les plus préparés franchissent la ligne.',
    tagline: 'Le triathlon le plus dur au monde',
    image_gradient: 'bg-gradient-to-br from-indigo-700 to-purple-800',
    avg_temp_celsius: 30,
    avg_water_temp_celsius: 20,
    avg_wind_kmh: 10,
    record_men: '9:23:00 — Marcel Zamora',
    record_women: '10:58:00 — Petra Eggenschwiler',
    tags: ['Mythique', 'Montagne', 'Extrême', 'Lac'],
    website_url: 'https://www.embrunman.com',
    finishers_url: 'https://www.finishers.com/course/embrunman',
  },
  {
    slug: 'challenge-roth',
    name: 'Challenge Roth',
    date: '2026-07-05',
    location: 'Roth, Bavière',
    city: 'Roth',
    department: null,
    region: 'Bavière',
    country: 'Allemagne',
    latitude: 49.2458,
    longitude: 11.0912,
    discipline: 'triathlon',
    category: 'XL',
    swim_distance: 3800,
    bike_distance: 180000,
    run_distance: 42195,
    total_distance: 226000,
    bike_elevation: 600,
    run_elevation: 100,
    total_elevation: 700,
    price_euros: 520,
    max_participants: 5500,
    time_limit_hours: 15.5,
    description: 'La course la plus rapide au monde sur distance Ironman. Parcours vélo très roulant dans la campagne bavaroise. Ambiance incroyable avec 250 000 spectateurs le long du parcours. La descente de Solarer Berg à vélo est légendaire.',
    tagline: 'The fastest long-distance race in the world',
    image_gradient: 'bg-gradient-to-br from-red-600 to-rose-700',
    avg_temp_celsius: 24,
    avg_water_temp_celsius: 21,
    avg_wind_kmh: 12,
    record_men: '7:35:39 — Jan Frodeno',
    record_women: '8:18:13 — Chrissie Wellington',
    tags: ['Mythique', 'Record', 'Plat', 'Ambiance', 'International'],
    website_url: 'https://www.challenge-roth.com',
    finishers_url: null,
  },
  {
    slug: 'norseman-xtreme-triathlon',
    name: 'Norseman Xtreme Triathlon',
    date: '2026-08-01',
    location: 'Eidfjord, Vestland',
    city: 'Eidfjord',
    department: null,
    region: 'Vestland',
    country: 'Norvège',
    latitude: 60.4648,
    longitude: 7.0722,
    discipline: 'triathlon',
    category: 'XL',
    swim_distance: 3800,
    bike_distance: 180000,
    run_distance: 42195,
    total_distance: 226000,
    bike_elevation: 3500,
    run_elevation: 1500,
    total_elevation: 5000,
    price_euros: 700,
    max_participants: 300,
    time_limit_hours: 18,
    description: 'Le triathlon extrême le plus célèbre au monde. Plongeon depuis un ferry dans les eaux glacées du fjord d\'Hardanger (14°C). Vélo à travers le plateau montagneux du Hardangervidda. Marathon qui se termine au sommet du Gaustatoppen à 1883m d\'altitude. Seuls les 160 premiers obtiennent le T-shirt noir.',
    tagline: 'The ultimate triathlon experience',
    image_gradient: 'bg-gradient-to-br from-slate-800 to-zinc-900',
    avg_temp_celsius: 15,
    avg_water_temp_celsius: 14,
    avg_wind_kmh: 20,
    record_men: '9:41:35 — Allan Hovda',
    record_women: '11:22:57 — Lisa Nordén',
    tags: ['Extrême', 'Montagne', 'Fjord', 'Aventure', 'International'],
    website_url: 'https://nxtri.com',
    finishers_url: null,
  },

  // ===================== 70.3 / Half =====================
  {
    slug: 'ironman-70-3-aix-en-provence',
    name: 'Ironman 70.3 Aix-en-Provence',
    date: '2026-05-17',
    location: 'Aix-en-Provence, Bouches-du-Rhône',
    city: 'Aix-en-Provence',
    department: 'Bouches-du-Rhône',
    region: 'Provence-Alpes-Côte d\'Azur',
    country: 'France',
    latitude: 43.5297,
    longitude: 5.4474,
    discipline: 'triathlon',
    category: '70.3',
    swim_distance: 1900,
    bike_distance: 90000,
    run_distance: 21100,
    total_distance: 113000,
    bike_elevation: 1170,
    run_elevation: 100,
    total_elevation: 1270,
    price_euros: 350,
    max_participants: 3000,
    time_limit_hours: 8.5,
    description: 'Course au cœur de la Provence. Nage au Lac de Peyrolles. Parcours vélo technique avec la montée de la Montagne Sainte-Victoire et le Col de Cengle. Course à pied sur 3 boucles entre le centre-ville et le Parc naturel de la Torse.',
    tagline: 'Une course d\'Aixpérience',
    image_gradient: 'bg-gradient-to-br from-yellow-500 to-orange-500',
    avg_temp_celsius: 25,
    avg_water_temp_celsius: 20,
    avg_wind_kmh: 15,
    record_men: null,
    record_women: null,
    tags: ['Provence', 'Technique', 'Lac', 'Montagne'],
    website_url: 'https://www.ironman.com/im703-aix',
    finishers_url: 'https://www.finishers.com/course/ironman-70-3-aix-en-provence',
  },
  {
    slug: 'ironman-70-3-versailles',
    name: 'Ironman 70.3 Versailles',
    date: '2026-07-12',
    location: 'Versailles, Yvelines',
    city: 'Versailles',
    department: 'Yvelines',
    region: 'Île-de-France',
    country: 'France',
    latitude: 48.8049,
    longitude: 2.1204,
    discipline: 'triathlon',
    category: '70.3',
    swim_distance: 1900,
    bike_distance: 90000,
    run_distance: 21100,
    total_distance: 113000,
    bike_elevation: 450,
    run_elevation: 80,
    total_elevation: 530,
    price_euros: 375,
    max_participants: 3000,
    time_limit_hours: 8.5,
    description: 'Première édition historique ! Triathlon au cœur du domaine royal de Versailles. Nage dans la pièce d\'eau des Suisses du Château. Vélo dans la Vallée de Chevreuse. Course à pied dans les jardins du Château de Versailles avec vue imprenable.',
    tagline: 'La course royale',
    image_gradient: 'bg-gradient-to-br from-amber-500 to-yellow-600',
    avg_temp_celsius: 24,
    avg_water_temp_celsius: 20,
    avg_wind_kmh: 12,
    record_men: null,
    record_women: null,
    tags: ['Nouveau', 'Historique', 'Prestige', 'Roulant'],
    website_url: 'https://www.ironman.com/im703-versailles',
    finishers_url: null,
  },
  {
    slug: 'ironman-70-3-les-sables-d-olonne',
    name: 'Ironman 70.3 Les Sables d\'Olonne',
    date: '2026-06-14',
    location: 'Les Sables-d\'Olonne, Vendée',
    city: 'Les Sables-d\'Olonne',
    department: 'Vendée',
    region: 'Pays de la Loire',
    country: 'France',
    latitude: 46.4974,
    longitude: -1.7830,
    discipline: 'triathlon',
    category: '70.3',
    swim_distance: 1900,
    bike_distance: 90000,
    run_distance: 21100,
    total_distance: 113000,
    bike_elevation: 380,
    run_elevation: 50,
    total_elevation: 430,
    price_euros: 340,
    max_participants: 2500,
    time_limit_hours: 8.5,
    description: 'Triathlon sur la côte atlantique vendéenne, ville de départ du Vendée Globe. Nage en mer dans la baie des Sables. Parcours vélo plat et rapide dans le marais poitevin. Semi-marathon le long du remblai avec une ambiance de folie.',
    tagline: 'L\'esprit Vendée Globe',
    image_gradient: 'bg-gradient-to-br from-teal-500 to-emerald-600',
    avg_temp_celsius: 21,
    avg_water_temp_celsius: 17,
    avg_wind_kmh: 20,
    record_men: null,
    record_women: null,
    tags: ['Bord de mer', 'Plat', 'Rapide', 'Ambiance'],
    website_url: 'https://www.ironman.com/im703-les-sables',
    finishers_url: null,
  },
  {
    slug: 'ironman-70-3-vichy',
    name: 'Ironman 70.3 Vichy',
    date: '2026-08-30',
    location: 'Vichy, Allier',
    city: 'Vichy',
    department: 'Allier',
    region: 'Auvergne-Rhône-Alpes',
    country: 'France',
    latitude: 46.1270,
    longitude: 3.4269,
    discipline: 'triathlon',
    category: '70.3',
    swim_distance: 1900,
    bike_distance: 90000,
    run_distance: 21100,
    total_distance: 113000,
    bike_elevation: 540,
    run_elevation: 60,
    total_elevation: 600,
    price_euros: 345,
    max_participants: 3000,
    time_limit_hours: 8.5,
    description: 'Course dans le cadre thermal de Vichy. Nage dans le lac d\'Allier. Parcours vélo vallonné dans les collines du Bourbonnais avec des paysages magnifiques. Course à pied le long des berges de l\'Allier et à travers les parcs de la ville.',
    tagline: 'La reine des eaux',
    image_gradient: 'bg-gradient-to-br from-sky-500 to-blue-600',
    avg_temp_celsius: 26,
    avg_water_temp_celsius: 22,
    avg_wind_kmh: 10,
    record_men: null,
    record_women: null,
    tags: ['Lac', 'Vallonné', 'Thermale', 'Fin de saison'],
    website_url: 'https://www.ironman.com/im703-vichy',
    finishers_url: null,
  },
  {
    slug: 'half-embrunman',
    name: 'Half Embrunman',
    date: '2026-08-15',
    location: 'Embrun, Hautes-Alpes',
    city: 'Embrun',
    department: 'Hautes-Alpes',
    region: 'Provence-Alpes-Côte d\'Azur',
    country: 'France',
    latitude: 44.5640,
    longitude: 6.4959,
    discipline: 'triathlon',
    category: '70.3',
    swim_distance: 1900,
    bike_distance: 90000,
    run_distance: 21100,
    total_distance: 113000,
    bike_elevation: 2350,
    run_elevation: 50,
    total_elevation: 2400,
    price_euros: 200,
    max_participants: 600,
    time_limit_hours: 9,
    description: 'Le petit frère de l\'Embrunman. Nage dans le lac de Serre-Ponçon. Parcours vélo de 90km avec 2350m de D+ sur 3 boucles. Course à pied sur 2 boucles autour d\'Embrun. Une excellente préparation pour le format complet.',
    tagline: 'Le goût de l\'extrême, format half',
    image_gradient: 'bg-gradient-to-br from-violet-600 to-indigo-700',
    avg_temp_celsius: 30,
    avg_water_temp_celsius: 20,
    avg_wind_kmh: 10,
    record_men: null,
    record_women: null,
    tags: ['Montagne', 'Lac', 'Exigeant', 'Préparation'],
    website_url: 'https://www.embrunman.com',
    finishers_url: 'https://www.finishers.com/course/embrunman',
  },

  // ===================== L (Long Distance) =====================
  {
    slug: 'triathlon-gerardmer-l',
    name: 'Triathlon de Gérardmer L',
    date: '2026-09-06',
    location: 'Gérardmer, Vosges',
    city: 'Gérardmer',
    department: 'Vosges',
    region: 'Grand Est',
    country: 'France',
    latitude: 48.0593,
    longitude: 6.8926,
    discipline: 'triathlon',
    category: 'L',
    swim_distance: 1900,
    bike_distance: 93000,
    run_distance: 21000,
    total_distance: 116000,
    bike_elevation: 1890,
    run_elevation: 240,
    total_elevation: 2130,
    price_euros: 120,
    max_participants: 1200,
    time_limit_hours: 9,
    description: 'La Perle des Vosges ! Nage dans le lac de Gérardmer. Vélo très exigeant sur 3 boucles de 31km avec 1890m de D+ à travers les forêts vosgiennes. Course à pied sur 3 boucles de 7km avec 240m de D+. Paysages magnifiques de lacs et forêts.',
    tagline: 'La vie en Vosges',
    image_gradient: 'bg-gradient-to-br from-emerald-600 to-green-700',
    avg_temp_celsius: 20,
    avg_water_temp_celsius: 18,
    avg_wind_kmh: 8,
    record_men: null,
    record_women: null,
    tags: ['Montagne', 'Lac', 'Forêt', 'Technique'],
    website_url: 'https://triathlondegerardmer.com',
    finishers_url: 'https://www.finishers.com/course/triathlon-de-gerardmer',
  },
  {
    slug: 'triathlon-deauville-l',
    name: 'Triathlon de Deauville L',
    date: '2026-06-21',
    location: 'Deauville, Calvados',
    city: 'Deauville',
    department: 'Calvados',
    region: 'Normandie',
    country: 'France',
    latitude: 49.3540,
    longitude: 0.0751,
    discipline: 'triathlon',
    category: 'L',
    swim_distance: 1900,
    bike_distance: 90000,
    run_distance: 21100,
    total_distance: 113000,
    bike_elevation: 500,
    run_elevation: 100,
    total_elevation: 600,
    price_euros: 150,
    max_participants: 1500,
    time_limit_hours: 8,
    description: 'Triathlon premium sur la côte normande. Nage en mer dans la Manche au départ des célèbres Planches de Deauville. Vélo dans le bocage normand vallonné. Semi-marathon le long du front de mer avec ambiance festive. L\'un des plus beaux triathlons de France.',
    tagline: 'Le triathlon chic',
    image_gradient: 'bg-gradient-to-br from-blue-500 to-indigo-600',
    avg_temp_celsius: 20,
    avg_water_temp_celsius: 16,
    avg_wind_kmh: 15,
    record_men: null,
    record_women: null,
    tags: ['Bord de mer', 'Prestige', 'Normandie', 'Ambiance'],
    website_url: 'https://triathlondeauville.com',
    finishers_url: 'https://www.finishers.com/course/triathlon-de-deauville',
  },
  {
    slug: 'chtriman',
    name: 'Ch\'Triman',
    date: '2026-06-07',
    location: 'Gravelines, Nord',
    city: 'Gravelines',
    department: 'Nord',
    region: 'Hauts-de-France',
    country: 'France',
    latitude: 50.9860,
    longitude: 2.1280,
    discipline: 'triathlon',
    category: 'L',
    swim_distance: 1900,
    bike_distance: 90000,
    run_distance: 21100,
    total_distance: 113000,
    bike_elevation: 150,
    run_elevation: 20,
    total_elevation: 170,
    price_euros: 130,
    max_participants: 2000,
    time_limit_hours: 8,
    description: 'Le triathlon le plus plat de France ! Nage dans le plan d\'eau de Gravelines. Vélo ultra-rapide sur routes plates des Flandres (attention au vent !). Semi-marathon plat mais exposé au vent. Idéal pour battre son record personnel si les conditions sont bonnes.',
    tagline: 'Le plat pays pour des records',
    image_gradient: 'bg-gradient-to-br from-zinc-600 to-zinc-800',
    avg_temp_celsius: 18,
    avg_water_temp_celsius: 16,
    avg_wind_kmh: 25,
    record_men: null,
    record_women: null,
    tags: ['Plat', 'Rapide', 'Record', 'Vent'],
    website_url: 'https://www.chtriman.com',
    finishers_url: null,
  },

  // ===================== M (Olympique) =====================
  {
    slug: 'triathlon-paris-m',
    name: 'Triathlon de Paris',
    date: '2026-07-05',
    location: 'Paris, Seine',
    city: 'Paris',
    department: 'Paris',
    region: 'Île-de-France',
    country: 'France',
    latitude: 48.8566,
    longitude: 2.3522,
    discipline: 'triathlon',
    category: 'M',
    swim_distance: 1500,
    bike_distance: 40000,
    run_distance: 10000,
    total_distance: 51500,
    bike_elevation: 120,
    run_elevation: 30,
    total_elevation: 150,
    price_euros: 95,
    max_participants: 4000,
    time_limit_hours: 4.5,
    description: 'Triathlon au cœur de la capitale ! Nage dans le bassin de La Villette. Vélo sur les quais de Seine, passage devant la Tour Eiffel et les Champs-Élysées. Course à pied dans le Bois de Vincennes. Une expérience unique de triathlon urbain.',
    tagline: 'Paris est un triathlon',
    image_gradient: 'bg-gradient-to-br from-rose-500 to-pink-600',
    avg_temp_celsius: 25,
    avg_water_temp_celsius: 20,
    avg_wind_kmh: 10,
    record_men: null,
    record_women: null,
    tags: ['Urbain', 'Prestige', 'Plat', 'Iconique'],
    website_url: 'https://www.triathlondeparis.com',
    finishers_url: null,
  },
  {
    slug: 'triathlon-annecy-m',
    name: 'Triathlon d\'Annecy',
    date: '2026-06-28',
    location: 'Annecy, Haute-Savoie',
    city: 'Annecy',
    department: 'Haute-Savoie',
    region: 'Auvergne-Rhône-Alpes',
    country: 'France',
    latitude: 45.8992,
    longitude: 6.1294,
    discipline: 'triathlon',
    category: 'M',
    swim_distance: 1500,
    bike_distance: 40000,
    run_distance: 10000,
    total_distance: 51500,
    bike_elevation: 350,
    run_elevation: 50,
    total_elevation: 400,
    price_euros: 85,
    max_participants: 1500,
    time_limit_hours: 4,
    description: 'Triathlon dans le lac le plus pur d\'Europe ! Nage dans les eaux turquoise du lac d\'Annecy (21°C). Parcours vélo vallonné avec vue sur les Alpes. Course à pied le long des berges avec panorama sur le château et les montagnes.',
    tagline: 'La Venise des Alpes',
    image_gradient: 'bg-gradient-to-br from-cyan-500 to-teal-600',
    avg_temp_celsius: 24,
    avg_water_temp_celsius: 21,
    avg_wind_kmh: 8,
    record_men: null,
    record_women: null,
    tags: ['Lac', 'Montagne', 'Alpes', 'Cadre exceptionnel'],
    website_url: null,
    finishers_url: null,
  },
  {
    slug: 'triathlon-la-baule-m',
    name: 'Triathlon de La Baule',
    date: '2026-09-20',
    location: 'La Baule, Loire-Atlantique',
    city: 'La Baule',
    department: 'Loire-Atlantique',
    region: 'Pays de la Loire',
    country: 'France',
    latitude: 47.2864,
    longitude: -2.3932,
    discipline: 'triathlon',
    category: 'M',
    swim_distance: 1500,
    bike_distance: 40000,
    run_distance: 10000,
    total_distance: 51500,
    bike_elevation: 90,
    run_elevation: 10,
    total_elevation: 100,
    price_euros: 80,
    max_participants: 2000,
    time_limit_hours: 4,
    description: 'Triathlon en bord de mer sur la plus belle baie d\'Europe. Nage dans l\'océan Atlantique au départ de la Grande Plage. Vélo plat et rapide dans les marais salants de Guérande. Course à pied le long du remblai et dans les pins.',
    tagline: 'La plus belle baie d\'Europe',
    image_gradient: 'bg-gradient-to-br from-sky-400 to-blue-500',
    avg_temp_celsius: 20,
    avg_water_temp_celsius: 18,
    avg_wind_kmh: 15,
    record_men: null,
    record_women: null,
    tags: ['Bord de mer', 'Plat', 'Rapide', 'Fin de saison'],
    website_url: null,
    finishers_url: null,
  },
  {
    slug: 'triathlon-gerardmer-m',
    name: 'Triathlon de Gérardmer M',
    date: '2026-09-06',
    location: 'Gérardmer, Vosges',
    city: 'Gérardmer',
    department: 'Vosges',
    region: 'Grand Est',
    country: 'France',
    latitude: 48.0593,
    longitude: 6.8926,
    discipline: 'triathlon',
    category: 'M',
    swim_distance: 1500,
    bike_distance: 40000,
    run_distance: 11000,
    total_distance: 52500,
    bike_elevation: 990,
    run_elevation: 140,
    total_elevation: 1130,
    price_euros: 90,
    max_participants: 1500,
    time_limit_hours: 5,
    description: 'Distance olympique sur les routes vosgiennes. Nage dans le lac de Gérardmer. Vélo exigeant avec 990m de D+ sur 3 boucles. Course à pied de 11km avec 140m de D+. Un vrai test de montagne sur format court.',
    tagline: 'La vie en Vosges — format olympique',
    image_gradient: 'bg-gradient-to-br from-green-500 to-emerald-600',
    avg_temp_celsius: 20,
    avg_water_temp_celsius: 18,
    avg_wind_kmh: 8,
    record_men: null,
    record_women: null,
    tags: ['Montagne', 'Lac', 'Forêt', 'Exigeant'],
    website_url: 'https://triathlondegerardmer.com',
    finishers_url: 'https://www.finishers.com/course/triathlon-de-gerardmer',
  },
  {
    slug: 'triathlon-marseille-m',
    name: 'Triathlon de Marseille',
    date: '2026-07-12',
    location: 'Marseille, Bouches-du-Rhône',
    city: 'Marseille',
    department: 'Bouches-du-Rhône',
    region: 'Provence-Alpes-Côte d\'Azur',
    country: 'France',
    latitude: 43.2965,
    longitude: 5.3698,
    discipline: 'triathlon',
    category: 'M',
    swim_distance: 1500,
    bike_distance: 40000,
    run_distance: 10000,
    total_distance: 51500,
    bike_elevation: 250,
    run_elevation: 50,
    total_elevation: 300,
    price_euros: 85,
    max_participants: 2000,
    time_limit_hours: 4,
    description: 'Triathlon au départ du Vieux-Port de Marseille. Nage en Méditerranée dans les eaux des calanques. Vélo le long de la corniche avec vue sur les îles du Frioul. Course à pied le long du littoral. Soleil et Mistral garantis.',
    tagline: 'Le tri provençal',
    image_gradient: 'bg-gradient-to-br from-amber-500 to-orange-600',
    avg_temp_celsius: 28,
    avg_water_temp_celsius: 22,
    avg_wind_kmh: 20,
    record_men: null,
    record_women: null,
    tags: ['Bord de mer', 'Méditerranée', 'Urbain', 'Soleil'],
    website_url: null,
    finishers_url: null,
  },

  // ===================== S (Sprint) =====================
  {
    slug: 'triathlon-nice-s',
    name: 'Triathlon de Nice S',
    date: '2026-06-28',
    location: 'Nice, Alpes-Maritimes',
    city: 'Nice',
    department: 'Alpes-Maritimes',
    region: 'Provence-Alpes-Côte d\'Azur',
    country: 'France',
    latitude: 43.7102,
    longitude: 7.2620,
    discipline: 'triathlon',
    category: 'S',
    swim_distance: 750,
    bike_distance: 20000,
    run_distance: 5000,
    total_distance: 25750,
    bike_elevation: 200,
    run_elevation: 10,
    total_elevation: 210,
    price_euros: 55,
    max_participants: 1000,
    time_limit_hours: 2.5,
    description: 'Format sprint le week-end de l\'Ironman France ! Nage dans la Baie des Anges. Vélo sur un parcours raccourci dans les collines niçoises. Course à pied sur la Promenade des Anglais. Parfait pour découvrir le triathlon dans un cadre exceptionnel.',
    tagline: 'Ton premier Ironman... en sprint',
    image_gradient: 'bg-gradient-to-br from-blue-400 to-cyan-500',
    avg_temp_celsius: 28,
    avg_water_temp_celsius: 23,
    avg_wind_kmh: 15,
    record_men: null,
    record_women: null,
    tags: ['Bord de mer', 'Découverte', 'Sprint', 'Soleil'],
    website_url: null,
    finishers_url: null,
  },
  {
    slug: 'triathlon-arcachon-s',
    name: 'Triathlon d\'Arcachon',
    date: '2026-06-14',
    location: 'Arcachon, Gironde',
    city: 'Arcachon',
    department: 'Gironde',
    region: 'Nouvelle-Aquitaine',
    country: 'France',
    latitude: 44.6611,
    longitude: -1.1681,
    discipline: 'triathlon',
    category: 'S',
    swim_distance: 750,
    bike_distance: 20000,
    run_distance: 5000,
    total_distance: 25750,
    bike_elevation: 50,
    run_elevation: 10,
    total_elevation: 60,
    price_euros: 50,
    max_participants: 800,
    time_limit_hours: 2,
    description: 'Sprint au cœur du Bassin d\'Arcachon. Nage dans les eaux du bassin face à la Dune du Pilat. Vélo plat dans les pistes cyclables de la forêt de pins. Course à pied sur le front de mer. Ambiance décontractée et festive.',
    tagline: 'Le sprint face à la Dune',
    image_gradient: 'bg-gradient-to-br from-yellow-400 to-amber-500',
    avg_temp_celsius: 23,
    avg_water_temp_celsius: 19,
    avg_wind_kmh: 12,
    record_men: null,
    record_women: null,
    tags: ['Bord de mer', 'Plat', 'Découverte', 'Décontracté'],
    website_url: null,
    finishers_url: null,
  },
];

async function seed() {
  // Supprimer les anciennes données
  const { error: delError } = await supabase
    .from('races')
    .delete()
    .neq('id', 0); // supprime tout

  if (delError) {
    console.error('Erreur suppression:', delError.message);
  } else {
    console.log('Anciennes courses supprimées');
  }

  // Insérer les nouvelles
  const { data, error } = await supabase
    .from('races')
    .insert(races)
    .select('id, slug, name, category');

  if (error) {
    console.error('Erreur insertion:', error.message);
    console.error('Détails:', error);
  } else {
    console.log(`\n${data.length} courses insérées :\n`);
    data.forEach(r => console.log(`  [${r.category.padEnd(7)}] ${r.name} (${r.slug})`));
  }
}

seed();
